// Generated by CoffeeScript 1.6.1
(function() {
  var _base, _ref, _ref1;

  if ((_ref = this.console) == null) {
    this.console = {};
  }

  if ((_ref1 = (_base = this.console).log) == null) {
    _base.log = function() {};
  }

  $(function() {
    var $buffer_bar, $play_button, $time_bar, $time_left, $video, cue, cues, current_time, duration, time_line, to_clock, to_s, _i, _len;
    $video = Popcorn('#the-video');
    $play_button = $('.button-play');
    $time_bar = $('.time-bar');
    $buffer_bar = $('.buffer_bar');
    $time_left = $('.time-left');
    duration = 0;
    current_time = 0;
    to_s = Popcorn.util.toSeconds;
    to_clock = function(seconds) {
      var min, s;
      min = Math.floor(seconds / 60);
      s = seconds % 60;
      min = min > 9 ? "" + min : "0" + min;
      s = s > 9 ? "" + s : "0" + s;
      return "" + min + ":" + s;
    };
    cues = [
      {
        type: "chapter",
        title: "A Safe Place",
        target: "#safety",
        time: "00:10"
      }, {
        type: "chapter",
        title: "Quality of Care",
        target: "#quality-of-care",
        time: "00:20"
      }, {
        type: "chapter",
        title: "Deceptively Simple",
        target: "#infection",
        time: "00:30"
      }, {
        type: "chapter",
        title: "Deny & Defend",
        target: "#culpability",
        time: "00:40"
      }, {
        type: "chapter",
        title: "Malpractice in Practice",
        target: "#lawsuit",
        time: "00:50"
      }, {
        type: "chapter",
        title: "Is It Getting Better?",
        target: "#no-improvement",
        time: "01:00"
      }
    ];
    for (_i = 0, _len = cues.length; _i < _len; _i++) {
      cue = cues[_i];
      if (cue.type === "chapter") {
        $('ul', '.chapter-list').append("<li><a href='" + cue.target + "'>" + cue.title + "</a></li>");
      }
    }
    $play_button.add('#the-video').on("click", function() {
      if ($play_button.hasClass("paused")) {
        $video.play();
      } else {
        $video.pause();
      }
      return $play_button.toggleClass("paused");
    });
    $('.progress').on("click", function(e) {
      var pos;
      pos = e.offsetX / $(this).width();
      return $video.currentTime(pos * duration);
    });
    $(document).on("keydown", function(e) {
      var left_arrow, right_arrow;
      left_arrow = 37;
      return right_arrow = 39;
    });
    $('a', '.chapter-list').on("click", function(e) {
      var cue_time, target, _j, _len1;
      e.preventDefault();
      $('.chapter').removeClass('current');
      $(this).addClass('current');
      target = $(this).attr('href');
      for (_j = 0, _len1 = cues.length; _j < _len1; _j++) {
        cue = cues[_j];
        if (cue.target === target) {
          cue_time = to_s(cue.time);
        }
      }
      $video.currentTime(cue_time).pause();
      $play_button.addClass('paused');
      $('.current-node').removeClass('current-node');
      return $(target).addClass('current-node');
    });
    $.each(cues, function(i, cue_item) {
      return $video.cue(to_s(cue_item.time), function() {
        $('.current-node').removeClass('current-node');
        return $(target).addClass('current-node');
      });
    });
    return (time_line = function() {
      current_time = $video.currentTime();
      duration = $video.duration() || 0;
      $time_bar.css({
        left: "" + (current_time / duration * 100) + "%"
      });
      $time_left.text(to_clock(Math.floor(duration - current_time)));
      return setTimeout(time_line, 200);
    })();
  });

}).call(this);
